-- 005_seed_disallowed_users.sql
-- Pre-populate blocked usernames (hardcoded system accounts)
-- Source: 00810_disallowed_users.sql (data portion)

INSERT IGNORE INTO disallowed_users (username, reason, is_hardcoded, created_by) VALUES
-- Core system accounts
('root', 'System administrator account', TRUE, NULL),
('daemon', 'System daemon account', TRUE, NULL),
('bin', 'System binary owner', TRUE, NULL),
('sys', 'System account', TRUE, NULL),
('sync', 'System sync account', TRUE, NULL),
('games', 'Games pseudo-user', TRUE, NULL),
('man', 'Man page owner', TRUE, NULL),
('lp', 'Line printer daemon', TRUE, NULL),
('mail', 'Mail daemon', TRUE, NULL),
('news', 'News daemon', TRUE, NULL),
('uucp', 'UUCP daemon', TRUE, NULL),
('proxy', 'Proxy daemon', TRUE, NULL),
('backup', 'Backup daemon', TRUE, NULL),
('list', 'Mailing list manager', TRUE, NULL),
('irc', 'IRC daemon', TRUE, NULL),
('gnats', 'Bug reporting system', TRUE, NULL),
('nobody', 'Unprivileged user', TRUE, NULL),
-- Systemd accounts
('systemd-network', 'Systemd network daemon', TRUE, NULL),
('systemd-resolve', 'Systemd resolver', TRUE, NULL),
('systemd-timesync', 'Systemd time sync', TRUE, NULL),
('messagebus', 'D-Bus message daemon', TRUE, NULL),
('syslog', 'Syslog daemon', TRUE, NULL),
-- Package/service accounts
('_apt', 'APT package manager', TRUE, NULL),
('tss', 'TPM software stack', TRUE, NULL),
('uuidd', 'UUID daemon', TRUE, NULL),
('tcpdump', 'Network packet analyzer', TRUE, NULL),
('avahi-autoipd', 'Avahi autoip daemon', TRUE, NULL),
('usbmux', 'USB multiplexer', TRUE, NULL),
('rtkit', 'RealtimeKit daemon', TRUE, NULL),
('dnsmasq', 'DNS/DHCP server', TRUE, NULL),
('cups-pk-helper', 'CUPS policy kit helper', TRUE, NULL),
('speech-dispatcher', 'Speech synthesis daemon', TRUE, NULL),
('avahi', 'Avahi mDNS daemon', TRUE, NULL),
('kernoops', 'Kernel oops collector', TRUE, NULL),
('saned', 'SANE scanner daemon', TRUE, NULL),
('nm-openvpn', 'NetworkManager OpenVPN', TRUE, NULL),
('hplip', 'HP Linux Imaging', TRUE, NULL),
('whoopsie', 'Ubuntu error reporting', TRUE, NULL),
('colord', 'Color management daemon', TRUE, NULL),
('geoclue', 'Geolocation daemon', TRUE, NULL),
('pulse', 'PulseAudio daemon', TRUE, NULL),
('gnome-initial-setup', 'GNOME initial setup', TRUE, NULL),
('gdm', 'GNOME display manager', TRUE, NULL),
('sssd', 'System security services', TRUE, NULL),
-- Web/database service accounts
('www-data', 'Web server daemon', TRUE, NULL),
('mysql', 'MySQL server', TRUE, NULL),
('postgres', 'PostgreSQL server', TRUE, NULL),
('redis', 'Redis server', TRUE, NULL),
('nginx', 'Nginx web server', TRUE, NULL),
('apache', 'Apache web server', TRUE, NULL),
('apache2', 'Apache2 web server', TRUE, NULL),
('httpd', 'HTTP daemon', TRUE, NULL),
-- Cloud/VM accounts
('ubuntu', 'Ubuntu default user', TRUE, NULL),
('ec2-user', 'AWS EC2 default user', TRUE, NULL),
('admin', 'Generic admin account', TRUE, NULL),
-- Reserved pullDB names
('pulldb', 'pullDB service name', TRUE, NULL),
('pulldb_service', 'Service Bootstrap/CLI Admin Account (sbcacc)', TRUE, NULL),
('system', 'Reserved system name', TRUE, NULL),
('service', 'Reserved service name', TRUE, NULL),
('api', 'Reserved API name', TRUE, NULL),
('web', 'Reserved web name', TRUE, NULL),
('worker', 'Reserved worker name', TRUE, NULL),
('anonymous', 'Anonymous user concept', TRUE, NULL),
('guest', 'Guest user concept', TRUE, NULL),
('test', 'Test account name', TRUE, NULL),
('demo', 'Demo account name', TRUE, NULL);
